CREATE TABLE IF NOT EXISTS USERS
(
    USER_ID   INTEGER AUTO_INCREMENT,
    EMAIL     CHARACTER VARYING(200) NOT NULL,
    LOGIN     CHARACTER VARYING(200) NOT NULL,
    USER_NAME CHARACTER VARYING(200) NOT NULL,
    BIRTHDAY  DATE,
    CONSTRAINT USERS_PK
        PRIMARY KEY (USER_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS USERS_EMAIL_UINDEX
    ON USERS (EMAIL);

CREATE UNIQUE INDEX IF NOT EXISTS USERS_LOGIN_UINDEX
    ON USERS (LOGIN);

CREATE TABLE IF NOT EXISTS MPA
(
    MPA_ID   INTEGER AUTO_INCREMENT,
    MPA_NAME CHARACTER VARYING(200) NOT NULL,
    CONSTRAINT MPA_PK
        PRIMARY KEY (MPA_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS MPA_MPA_NAME_UINDEX
    on MPA (MPA_NAME);

CREATE TABLE IF NOT EXISTS FILMS
(
    FILM_ID       INTEGER AUTO_INCREMENT,
    FILM_NAME     CHARACTER VARYING(255) NOT NULL,
    DESCRIPTION   CHARACTER VARYING(200) NOT NULL,
    RELEASE_DATE  DATE NOT NULL,
    DURATION      INTEGER NOT NULL,
    MPA_ID        INTEGER NOT NULL,
    CONSTRAINT FILMS_PK
        PRIMARY KEY (FILM_ID),
    FOREIGN KEY (MPA_ID) REFERENCES MPA (MPA_ID) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS GENRES
(
    GENRE_ID   INTEGER AUTO_INCREMENT,
    GENRE_NAME CHARACTER VARYING(200) NOT NULL,
    CONSTRAINT GENRE_PK
        PRIMARY KEY (GENRE_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS GENRES_GENRE_NAME_UINDEX
    on GENRES (GENRE_NAME);

CREATE TABLE IF NOT EXISTS FILM_GENRES
(
    FILM_ID  INTEGER NOT NULL,
    GENRE_ID INTEGER NOT NULL,
    FOREIGN KEY (FILM_ID) REFERENCES FILMS (FILM_ID) ON DELETE CASCADE,
    FOREIGN KEY (GENRE_ID) REFERENCES GENRES (GENRE_ID) ON DELETE CASCADE,
    PRIMARY KEY (FILM_ID, GENRE_ID)
);

CREATE TABLE IF NOT EXISTS FRIENDS
(
    USER_ID   INTEGER NOT NULL,
    FRIEND_ID INTEGER NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (FRIEND_ID) REFERENCES USERS (USER_ID) ON DELETE CASCADE,
    PRIMARY KEY (USER_ID, FRIEND_ID)
);

CREATE TABLE IF NOT EXISTS LIKES
(
    USER_ID INTEGER NOT NULL,
    FILM_ID INTEGER NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (FILM_ID) REFERENCES FILMS (FILM_ID) ON DELETE CASCADE,
    PRIMARY KEY (USER_ID, FILM_ID)
);

CREATE TABLE IF NOT EXISTS DIRECTORS
(
    DIRECTOR_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME        VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS FILMS_DIRECTORS
(
    FILM_ID     INTEGER REFERENCES FILMS(FILM_ID) ON DELETE CASCADE,
    DIRECTOR_ID INTEGER REFERENCES DIRECTORS(DIRECTOR_ID) ON DELETE CASCADE,
    CONSTRAINT FILMS_DIRECTORS_PK
        PRIMARY KEY (FILM_ID, DIRECTOR_ID)
);
